services:

  db:
    image: postgres:14.12
    restart: unless-stopped
    networks:
      - db
    env_file:
      - "env/postgres.env"
    volumes:
      - db_data:/var/lib/postgresql/data

  verkel:
    image: ghcr.io/buenaventure/verkel:main
    restart: unless-stopped
    networks:
      - db
      - proxy
    env_file:
      - "env/verkel.env"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/certs:/etc/ssl/certs/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

networks:
  db:
  proxy:

volumes:
  db_data:
